# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/.Xil/Vivado-9120-FXTVWR85EI30285/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7k325tffg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.cache/wt [current_project]
set_property parent.project_path C:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.srcs/sources_1/mac/arp_cache.v
  C:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.srcs/sources_1/mac/tx/arp_tx.v
  C:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.srcs/sources_1/mac/crc.v
  C:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.srcs/sources_1/new/ethernet_test.v
  C:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.srcs/sources_1/arbi/gmii_arbi.v
  C:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.srcs/sources_1/arbi/gmii_tx_buffer.v
  C:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.srcs/sources_1/mac/icmp_reply.v
  C:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.srcs/sources_1/mac/tx/ip_tx.v
  C:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.srcs/sources_1/mac/tx/ip_tx_mode.v
  C:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.srcs/sources_1/mac/mac_test.v
  C:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.srcs/sources_1/mac/mac_top.v
  C:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.srcs/sources_1/mac/tx/mac_tx.v
  C:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.srcs/sources_1/mac/tx/mac_tx_mode.v
  C:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.srcs/sources_1/mac/tx/mac_tx_top.v
  C:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.srcs/sources_1/mac/tx/udp_tx.v
  C:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.srcs/sources_1/new/util_gmii_to_rgmii.v
  C:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.srcs/sources_1/new/ethernet_top.v
}
read_ip -quiet C:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.srcs/sources_1/ip/icmp_rx_ram_8_256/icmp_rx_ram_8_256.xci
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.srcs/sources_1/ip/icmp_rx_ram_8_256/icmp_rx_ram_8_256_ooc.xdc]

read_ip -quiet C:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.srcs/sources_1/ip/udp_checksum_fifo/udp_checksum_fifo.xci
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.srcs/sources_1/ip/udp_checksum_fifo/udp_checksum_fifo.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.srcs/sources_1/ip/udp_checksum_fifo/udp_checksum_fifo_ooc.xdc]

read_ip -quiet C:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.srcs/sources_1/ip/udp_tx_data_fifo/udp_tx_data_fifo.xci
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.srcs/sources_1/ip/udp_tx_data_fifo/udp_tx_data_fifo.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.srcs/sources_1/ip/udp_tx_data_fifo/udp_tx_data_fifo_ooc.xdc]

read_ip -quiet C:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.srcs/sources_1/ip/len_fifo/len_fifo.xci
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.srcs/sources_1/ip/len_fifo/len_fifo.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.srcs/sources_1/ip/len_fifo/len_fifo_ooc.xdc]

read_ip -quiet C:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.srcs/sources_1/ip/eth_data_fifo/eth_data_fifo.xci
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.srcs/sources_1/ip/eth_data_fifo/eth_data_fifo.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.srcs/sources_1/ip/eth_data_fifo/eth_data_fifo_ooc.xdc]

read_ip -quiet C:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.srcs/sources_1/ip/clk_ref/clk_ref.xci
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.srcs/sources_1/ip/clk_ref/clk_ref_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.srcs/sources_1/ip/clk_ref/clk_ref.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.srcs/sources_1/ip/clk_ref/clk_ref_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.srcs/constrs_1/new/top.xdc
set_property used_in_implementation false [get_files C:/Users/Administrator/Desktop/ETH1_BACK/k720_rgmii_eth2_udp_send/eth_test.srcs/constrs_1/new/top.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top ethernet_top -part xc7k325tffg676-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ethernet_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ethernet_top_utilization_synth.rpt -pb ethernet_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
