# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7k325tffg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Administrator/Desktop/K7325/DEMO/k714_ov5640_rgb_to_ycbcr/k714_ov5640_rgb_to_ycbcr.cache/wt [current_project]
set_property parent.project_path C:/Users/Administrator/Desktop/K7325/DEMO/k714_ov5640_rgb_to_ycbcr/k714_ov5640_rgb_to_ycbcr.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/Administrator/Desktop/K7325/DEMO/k714_ov5640_rgb_to_ycbcr/tmds_ip [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/Administrator/Desktop/K7325/DEMO/k714_ov5640_rgb_to_ycbcr/k714_ov5640_rgb_to_ycbcr.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Administrator/Desktop/K7325/DEMO/k714_ov5640_rgb_to_ycbcr/k714_ov5640_rgb_to_ycbcr.srcs/sources_1/new/i2c_driver.v
  C:/Users/Administrator/Desktop/K7325/DEMO/k714_ov5640_rgb_to_ycbcr/k714_ov5640_rgb_to_ycbcr.srcs/sources_1/new/ov5640_capture.v
  C:/Users/Administrator/Desktop/K7325/DEMO/k714_ov5640_rgb_to_ycbcr/k714_ov5640_rgb_to_ycbcr.srcs/sources_1/new/ov5640_reg_config.v
  C:/Users/Administrator/Desktop/K7325/DEMO/k714_ov5640_rgb_to_ycbcr/k714_ov5640_rgb_to_ycbcr.srcs/sources_1/new/power_on_reset.v
  C:/Users/Administrator/Desktop/K7325/DEMO/k714_ov5640_rgb_to_ycbcr/k714_ov5640_rgb_to_ycbcr.srcs/sources_1/new/vga_driver.v
  C:/Users/Administrator/Desktop/K7325/DEMO/k714_ov5640_rgb_to_ycbcr/k714_ov5640_rgb_to_ycbcr.srcs/sources_1/new/vga_sync.v
  C:/Users/Administrator/Desktop/K7325/DEMO/k714_ov5640_rgb_to_ycbcr/k714_ov5640_rgb_to_ycbcr.srcs/sources_1/new/rgb_to_ycbcr.v
}
read_ip -quiet C:/Users/Administrator/Desktop/K7325/DEMO/k714_ov5640_rgb_to_ycbcr/k714_ov5640_rgb_to_ycbcr.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/K7325/DEMO/k714_ov5640_rgb_to_ycbcr/k714_ov5640_rgb_to_ycbcr.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

read_ip -quiet C:/Users/Administrator/Desktop/K7325/DEMO/k714_ov5640_rgb_to_ycbcr/k714_ov5640_rgb_to_ycbcr.srcs/sources_1/ip/rgb2dvi_0/rgb2dvi_0.xci
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/K7325/DEMO/k714_ov5640_rgb_to_ycbcr/k714_ov5640_rgb_to_ycbcr.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/K7325/DEMO/k714_ov5640_rgb_to_ycbcr/k714_ov5640_rgb_to_ycbcr.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/K7325/DEMO/k714_ov5640_rgb_to_ycbcr/k714_ov5640_rgb_to_ycbcr.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi_clocks.xdc]

read_ip -quiet C:/Users/Administrator/Desktop/K7325/DEMO/k714_ov5640_rgb_to_ycbcr/k714_ov5640_rgb_to_ycbcr.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/K7325/DEMO/k714_ov5640_rgb_to_ycbcr/k714_ov5640_rgb_to_ycbcr.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/K7325/DEMO/k714_ov5640_rgb_to_ycbcr/k714_ov5640_rgb_to_ycbcr.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/K7325/DEMO/k714_ov5640_rgb_to_ycbcr/k714_ov5640_rgb_to_ycbcr.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Administrator/Desktop/K7325/DEMO/k714_ov5640_rgb_to_ycbcr/k714_ov5640_rgb_to_ycbcr.srcs/constrs_1/new/rgb_to_ycbcr.xdc
set_property used_in_implementation false [get_files C:/Users/Administrator/Desktop/K7325/DEMO/k714_ov5640_rgb_to_ycbcr/k714_ov5640_rgb_to_ycbcr.srcs/constrs_1/new/rgb_to_ycbcr.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top rgb_to_ycbcr -part xc7k325tffg676-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef rgb_to_ycbcr.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file rgb_to_ycbcr_utilization_synth.rpt -pb rgb_to_ycbcr_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
