set_property SRC_FILE_INFO {cfile:c:/Users/Administrator/Desktop/K7325/DEMO/k716_ddr3_read_write/k716_ddr3_read_write.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0.xdc rfile:../../../k716_ddr3_read_write.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0.xdc id:1 order:EARLY scoped_inst:mig_7series_0_inst} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/Administrator/Desktop/K7325/DEMO/k716_ddr3_read_write/k716_ddr3_read_write.srcs/constrs_1/new/ddr3_read_write.xdc rfile:../../../k716_ddr3_read_write.srcs/constrs_1/new/ddr3_read_write.xdc id:2} [current_design]
current_instance mig_7series_0_inst
set_property src_info {type:SCOPED_XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF14 [get_ports {ddr3_dq[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF17 [get_ports {ddr3_dq[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE15 [get_ports {ddr3_dq[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE17 [get_ports {ddr3_dq[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD15 [get_ports {ddr3_dq[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF20 [get_ports {ddr3_dq[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF15 [get_ports {ddr3_dq[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF19 [get_ports {ddr3_dq[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB15 [get_ports {ddr3_dq[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC14 [get_ports {ddr3_dq[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA18 [get_ports {ddr3_dq[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA14 [get_ports {ddr3_dq[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD14 [get_ports {ddr3_dq[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB14 [get_ports {ddr3_dq[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA17 [get_ports {ddr3_dq[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA15 [get_ports {ddr3_dq[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB17 [get_ports {ddr3_dq[16]}]
set_property src_info {type:SCOPED_XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB19 [get_ports {ddr3_dq[17]}]
set_property src_info {type:SCOPED_XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC17 [get_ports {ddr3_dq[18]}]
set_property src_info {type:SCOPED_XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA20 [get_ports {ddr3_dq[19]}]
set_property src_info {type:SCOPED_XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC18 [get_ports {ddr3_dq[20]}]
set_property src_info {type:SCOPED_XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA19 [get_ports {ddr3_dq[21]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC19 [get_ports {ddr3_dq[22]}]
set_property src_info {type:SCOPED_XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD19 [get_ports {ddr3_dq[23]}]
set_property src_info {type:SCOPED_XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y17 [get_ports {ddr3_dq[24]}]
set_property src_info {type:SCOPED_XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V16 [get_ports {ddr3_dq[25]}]
set_property src_info {type:SCOPED_XDC file:1 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V19 [get_ports {ddr3_dq[26]}]
set_property src_info {type:SCOPED_XDC file:1 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W16 [get_ports {ddr3_dq[27]}]
set_property src_info {type:SCOPED_XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports {ddr3_dq[28]}]
set_property src_info {type:SCOPED_XDC file:1 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W14 [get_ports {ddr3_dq[29]}]
set_property src_info {type:SCOPED_XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V18 [get_ports {ddr3_dq[30]}]
set_property src_info {type:SCOPED_XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W15 [get_ports {ddr3_dq[31]}]
set_property src_info {type:SCOPED_XDC file:1 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y7 [get_ports {ddr3_addr[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V7 [get_ports {ddr3_addr[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V9 [get_ports {ddr3_addr[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y11 [get_ports {ddr3_addr[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC9 [get_ports {ddr3_addr[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB7 [get_ports {ddr3_addr[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA7 [get_ports {ddr3_addr[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V8 [get_ports {ddr3_addr[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:281 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y10 [get_ports {ddr3_addr[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC8 [get_ports {ddr3_addr[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:293 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC11 [get_ports {ddr3_addr[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF7 [get_ports {ddr3_addr[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:305 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD8 [get_ports {ddr3_addr[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA10 [get_ports {ddr3_addr[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:317 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF8 [get_ports {ddr3_addr[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:323 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W8 [get_ports {ddr3_ba[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:329 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB11 [get_ports {ddr3_ba[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:335 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W9 [get_ports {ddr3_ba[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:341 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA8 [get_ports {ddr3_ras_n}]
set_property src_info {type:SCOPED_XDC file:1 line:347 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W10 [get_ports {ddr3_cas_n}]
set_property src_info {type:SCOPED_XDC file:1 line:353 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF9 [get_ports {ddr3_we_n}]
set_property src_info {type:SCOPED_XDC file:1 line:359 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF10 [get_ports {ddr3_reset_n}]
set_property src_info {type:SCOPED_XDC file:1 line:365 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB10 [get_ports {ddr3_cke[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:371 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD9 [get_ports {ddr3_odt[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:377 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y8 [get_ports {ddr3_cs_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:383 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD16 [get_ports {ddr3_dm[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:389 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB16 [get_ports {ddr3_dm[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:395 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD18 [get_ports {ddr3_dm[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:401 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V14 [get_ports {ddr3_dm[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:407 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE18 [get_ports {ddr3_dqs_p[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:413 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF18 [get_ports {ddr3_dqs_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:419 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y15 [get_ports {ddr3_dqs_p[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:425 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y16 [get_ports {ddr3_dqs_n[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:431 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD20 [get_ports {ddr3_dqs_p[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:437 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE20 [get_ports {ddr3_dqs_n[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:443 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W18 [get_ports {ddr3_dqs_p[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:449 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W19 [get_ports {ddr3_dqs_n[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:455 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA9 [get_ports {ddr3_ck_p[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:461 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB9 [get_ports {ddr3_ck_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:466 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y3 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:467 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y2 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:468 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y1 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:469 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y0 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:470 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y7 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:471 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y6 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:472 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y5 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:473 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y4 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:476 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y3 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:477 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y2 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:478 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y1 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:479 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y0 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:489 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y3 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:490 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y2 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:491 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y1 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:492 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y0 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:493 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y7 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:494 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y6 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:495 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y5 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:496 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y4 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:499 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y3 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:500 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y2 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:501 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y1 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:502 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y0 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:505 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y0 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:SCOPED_XDC file:1 line:506 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y1 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:SCOPED_XDC file:1 line:509 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y0 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:SCOPED_XDC file:1 line:510 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y1 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:SCOPED_XDC file:1 line:513 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y43 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:514 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y31 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:515 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y19 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:516 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y7 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:520 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PLLE2_ADV_X1Y1 [get_cells -hier -filter {NAME =~ */u_ddr3_infrastructure/plle2_i}]
set_property src_info {type:SCOPED_XDC file:1 line:521 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC MMCME2_ADV_X1Y1 [get_cells -hier -filter {NAME =~ */u_ddr3_infrastructure/gen_mmcm.mmcm_i}]
set_property src_info {type:SCOPED_XDC file:1 line:529 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -from [get_cells -hier -filter {NAME =~ */mc0/mc_read_idle_r_reg}] -to   [get_cells -hier -filter {NAME =~ */input_[?].iserdes_dq_.iserdesdq}] -hold 5
set_property src_info {type:SCOPED_XDC file:1 line:536 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -through [get_pins -filter {NAME =~ */OSERDESRST} -of [get_cells -hier -filter {REF_NAME == PHASER_OUT_PHY}]] -hold 1 -start
set_property src_info {type:SCOPED_XDC file:1 line:540 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hier *rstdiv0_sync_r1_reg*] -to [get_pins -filter {NAME =~ */RESET} -of [get_cells -hier -filter {REF_NAME == PHY_CONTROL}]] -datapath_only 5
current_instance
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G22 [get_ports sys_clk]
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A23 [get_ports calib_done]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D23 [get_ports locked]
set_property src_info {type:XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D26 [get_ports rstn]
set_property src_info {type:XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {debug_cnt_reg[0]} {debug_cnt_reg[1]} {debug_cnt_reg[2]} {debug_cnt_reg[3]} {debug_cnt_reg[4]} {debug_cnt_reg[5]} {debug_cnt_reg[6]} {debug_cnt_reg[7]} {debug_cnt_reg[8]} {debug_cnt_reg[9]} {debug_cnt_reg[10]} {debug_cnt_reg[11]} {debug_cnt_reg[12]} {debug_cnt_reg[13]} {debug_cnt_reg[14]} {debug_cnt_reg[15]}]]
set_property src_info {type:XDC file:2 line:15 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets debug_clk]
set_property src_info {type:XDC file:2 line:21 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:2 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:2 line:31 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list mig_7series_0_inst/u_mig_7series_0_mig/u_ddr3_infrastructure/CLK]]
set_property src_info {type:XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 256 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:34 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {app_rd_data[0]} {app_rd_data[1]} {app_rd_data[2]} {app_rd_data[3]} {app_rd_data[4]} {app_rd_data[5]} {app_rd_data[6]} {app_rd_data[7]} {app_rd_data[8]} {app_rd_data[9]} {app_rd_data[10]} {app_rd_data[11]} {app_rd_data[12]} {app_rd_data[13]} {app_rd_data[14]} {app_rd_data[15]} {app_rd_data[16]} {app_rd_data[17]} {app_rd_data[18]} {app_rd_data[19]} {app_rd_data[20]} {app_rd_data[21]} {app_rd_data[22]} {app_rd_data[23]} {app_rd_data[24]} {app_rd_data[25]} {app_rd_data[26]} {app_rd_data[27]} {app_rd_data[28]} {app_rd_data[29]} {app_rd_data[30]} {app_rd_data[31]} {app_rd_data[32]} {app_rd_data[33]} {app_rd_data[34]} {app_rd_data[35]} {app_rd_data[36]} {app_rd_data[37]} {app_rd_data[38]} {app_rd_data[39]} {app_rd_data[40]} {app_rd_data[41]} {app_rd_data[42]} {app_rd_data[43]} {app_rd_data[44]} {app_rd_data[45]} {app_rd_data[46]} {app_rd_data[47]} {app_rd_data[48]} {app_rd_data[49]} {app_rd_data[50]} {app_rd_data[51]} {app_rd_data[52]} {app_rd_data[53]} {app_rd_data[54]} {app_rd_data[55]} {app_rd_data[56]} {app_rd_data[57]} {app_rd_data[58]} {app_rd_data[59]} {app_rd_data[60]} {app_rd_data[61]} {app_rd_data[62]} {app_rd_data[63]} {app_rd_data[64]} {app_rd_data[65]} {app_rd_data[66]} {app_rd_data[67]} {app_rd_data[68]} {app_rd_data[69]} {app_rd_data[70]} {app_rd_data[71]} {app_rd_data[72]} {app_rd_data[73]} {app_rd_data[74]} {app_rd_data[75]} {app_rd_data[76]} {app_rd_data[77]} {app_rd_data[78]} {app_rd_data[79]} {app_rd_data[80]} {app_rd_data[81]} {app_rd_data[82]} {app_rd_data[83]} {app_rd_data[84]} {app_rd_data[85]} {app_rd_data[86]} {app_rd_data[87]} {app_rd_data[88]} {app_rd_data[89]} {app_rd_data[90]} {app_rd_data[91]} {app_rd_data[92]} {app_rd_data[93]} {app_rd_data[94]} {app_rd_data[95]} {app_rd_data[96]} {app_rd_data[97]} {app_rd_data[98]} {app_rd_data[99]} {app_rd_data[100]} {app_rd_data[101]} {app_rd_data[102]} {app_rd_data[103]} {app_rd_data[104]} {app_rd_data[105]} {app_rd_data[106]} {app_rd_data[107]} {app_rd_data[108]} {app_rd_data[109]} {app_rd_data[110]} {app_rd_data[111]} {app_rd_data[112]} {app_rd_data[113]} {app_rd_data[114]} {app_rd_data[115]} {app_rd_data[116]} {app_rd_data[117]} {app_rd_data[118]} {app_rd_data[119]} {app_rd_data[120]} {app_rd_data[121]} {app_rd_data[122]} {app_rd_data[123]} {app_rd_data[124]} {app_rd_data[125]} {app_rd_data[126]} {app_rd_data[127]} {app_rd_data[128]} {app_rd_data[129]} {app_rd_data[130]} {app_rd_data[131]} {app_rd_data[132]} {app_rd_data[133]} {app_rd_data[134]} {app_rd_data[135]} {app_rd_data[136]} {app_rd_data[137]} {app_rd_data[138]} {app_rd_data[139]} {app_rd_data[140]} {app_rd_data[141]} {app_rd_data[142]} {app_rd_data[143]} {app_rd_data[144]} {app_rd_data[145]} {app_rd_data[146]} {app_rd_data[147]} {app_rd_data[148]} {app_rd_data[149]} {app_rd_data[150]} {app_rd_data[151]} {app_rd_data[152]} {app_rd_data[153]} {app_rd_data[154]} {app_rd_data[155]} {app_rd_data[156]} {app_rd_data[157]} {app_rd_data[158]} {app_rd_data[159]} {app_rd_data[160]} {app_rd_data[161]} {app_rd_data[162]} {app_rd_data[163]} {app_rd_data[164]} {app_rd_data[165]} {app_rd_data[166]} {app_rd_data[167]} {app_rd_data[168]} {app_rd_data[169]} {app_rd_data[170]} {app_rd_data[171]} {app_rd_data[172]} {app_rd_data[173]} {app_rd_data[174]} {app_rd_data[175]} {app_rd_data[176]} {app_rd_data[177]} {app_rd_data[178]} {app_rd_data[179]} {app_rd_data[180]} {app_rd_data[181]} {app_rd_data[182]} {app_rd_data[183]} {app_rd_data[184]} {app_rd_data[185]} {app_rd_data[186]} {app_rd_data[187]} {app_rd_data[188]} {app_rd_data[189]} {app_rd_data[190]} {app_rd_data[191]} {app_rd_data[192]} {app_rd_data[193]} {app_rd_data[194]} {app_rd_data[195]} {app_rd_data[196]} {app_rd_data[197]} {app_rd_data[198]} {app_rd_data[199]} {app_rd_data[200]} {app_rd_data[201]} {app_rd_data[202]} {app_rd_data[203]} {app_rd_data[204]} {app_rd_data[205]} {app_rd_data[206]} {app_rd_data[207]} {app_rd_data[208]} {app_rd_data[209]} {app_rd_data[210]} {app_rd_data[211]} {app_rd_data[212]} {app_rd_data[213]} {app_rd_data[214]} {app_rd_data[215]} {app_rd_data[216]} {app_rd_data[217]} {app_rd_data[218]} {app_rd_data[219]} {app_rd_data[220]} {app_rd_data[221]} {app_rd_data[222]} {app_rd_data[223]} {app_rd_data[224]} {app_rd_data[225]} {app_rd_data[226]} {app_rd_data[227]} {app_rd_data[228]} {app_rd_data[229]} {app_rd_data[230]} {app_rd_data[231]} {app_rd_data[232]} {app_rd_data[233]} {app_rd_data[234]} {app_rd_data[235]} {app_rd_data[236]} {app_rd_data[237]} {app_rd_data[238]} {app_rd_data[239]} {app_rd_data[240]} {app_rd_data[241]} {app_rd_data[242]} {app_rd_data[243]} {app_rd_data[244]} {app_rd_data[245]} {app_rd_data[246]} {app_rd_data[247]} {app_rd_data[248]} {app_rd_data[249]} {app_rd_data[250]} {app_rd_data[251]} {app_rd_data[252]} {app_rd_data[253]} {app_rd_data[254]} {app_rd_data[255]}]]
set_property src_info {type:XDC file:2 line:35 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 29 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:38 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {app_addr[0]} {app_addr[1]} {app_addr[2]} {app_addr[3]} {app_addr[4]} {app_addr[5]} {app_addr[6]} {app_addr[7]} {app_addr[8]} {app_addr[9]} {app_addr[10]} {app_addr[11]} {app_addr[12]} {app_addr[13]} {app_addr[14]} {app_addr[15]} {app_addr[16]} {app_addr[17]} {app_addr[18]} {app_addr[19]} {app_addr[20]} {app_addr[21]} {app_addr[22]} {app_addr[23]} {app_addr[24]} {app_addr[25]} {app_addr[26]} {app_addr[27]} {app_addr[28]}]]
set_property src_info {type:XDC file:2 line:39 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 256 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:42 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {app_rd_data_reg[0]} {app_rd_data_reg[1]} {app_rd_data_reg[2]} {app_rd_data_reg[3]} {app_rd_data_reg[4]} {app_rd_data_reg[5]} {app_rd_data_reg[6]} {app_rd_data_reg[7]} {app_rd_data_reg[8]} {app_rd_data_reg[9]} {app_rd_data_reg[10]} {app_rd_data_reg[11]} {app_rd_data_reg[12]} {app_rd_data_reg[13]} {app_rd_data_reg[14]} {app_rd_data_reg[15]} {app_rd_data_reg[16]} {app_rd_data_reg[17]} {app_rd_data_reg[18]} {app_rd_data_reg[19]} {app_rd_data_reg[20]} {app_rd_data_reg[21]} {app_rd_data_reg[22]} {app_rd_data_reg[23]} {app_rd_data_reg[24]} {app_rd_data_reg[25]} {app_rd_data_reg[26]} {app_rd_data_reg[27]} {app_rd_data_reg[28]} {app_rd_data_reg[29]} {app_rd_data_reg[30]} {app_rd_data_reg[31]} {app_rd_data_reg[32]} {app_rd_data_reg[33]} {app_rd_data_reg[34]} {app_rd_data_reg[35]} {app_rd_data_reg[36]} {app_rd_data_reg[37]} {app_rd_data_reg[38]} {app_rd_data_reg[39]} {app_rd_data_reg[40]} {app_rd_data_reg[41]} {app_rd_data_reg[42]} {app_rd_data_reg[43]} {app_rd_data_reg[44]} {app_rd_data_reg[45]} {app_rd_data_reg[46]} {app_rd_data_reg[47]} {app_rd_data_reg[48]} {app_rd_data_reg[49]} {app_rd_data_reg[50]} {app_rd_data_reg[51]} {app_rd_data_reg[52]} {app_rd_data_reg[53]} {app_rd_data_reg[54]} {app_rd_data_reg[55]} {app_rd_data_reg[56]} {app_rd_data_reg[57]} {app_rd_data_reg[58]} {app_rd_data_reg[59]} {app_rd_data_reg[60]} {app_rd_data_reg[61]} {app_rd_data_reg[62]} {app_rd_data_reg[63]} {app_rd_data_reg[64]} {app_rd_data_reg[65]} {app_rd_data_reg[66]} {app_rd_data_reg[67]} {app_rd_data_reg[68]} {app_rd_data_reg[69]} {app_rd_data_reg[70]} {app_rd_data_reg[71]} {app_rd_data_reg[72]} {app_rd_data_reg[73]} {app_rd_data_reg[74]} {app_rd_data_reg[75]} {app_rd_data_reg[76]} {app_rd_data_reg[77]} {app_rd_data_reg[78]} {app_rd_data_reg[79]} {app_rd_data_reg[80]} {app_rd_data_reg[81]} {app_rd_data_reg[82]} {app_rd_data_reg[83]} {app_rd_data_reg[84]} {app_rd_data_reg[85]} {app_rd_data_reg[86]} {app_rd_data_reg[87]} {app_rd_data_reg[88]} {app_rd_data_reg[89]} {app_rd_data_reg[90]} {app_rd_data_reg[91]} {app_rd_data_reg[92]} {app_rd_data_reg[93]} {app_rd_data_reg[94]} {app_rd_data_reg[95]} {app_rd_data_reg[96]} {app_rd_data_reg[97]} {app_rd_data_reg[98]} {app_rd_data_reg[99]} {app_rd_data_reg[100]} {app_rd_data_reg[101]} {app_rd_data_reg[102]} {app_rd_data_reg[103]} {app_rd_data_reg[104]} {app_rd_data_reg[105]} {app_rd_data_reg[106]} {app_rd_data_reg[107]} {app_rd_data_reg[108]} {app_rd_data_reg[109]} {app_rd_data_reg[110]} {app_rd_data_reg[111]} {app_rd_data_reg[112]} {app_rd_data_reg[113]} {app_rd_data_reg[114]} {app_rd_data_reg[115]} {app_rd_data_reg[116]} {app_rd_data_reg[117]} {app_rd_data_reg[118]} {app_rd_data_reg[119]} {app_rd_data_reg[120]} {app_rd_data_reg[121]} {app_rd_data_reg[122]} {app_rd_data_reg[123]} {app_rd_data_reg[124]} {app_rd_data_reg[125]} {app_rd_data_reg[126]} {app_rd_data_reg[127]} {app_rd_data_reg[128]} {app_rd_data_reg[129]} {app_rd_data_reg[130]} {app_rd_data_reg[131]} {app_rd_data_reg[132]} {app_rd_data_reg[133]} {app_rd_data_reg[134]} {app_rd_data_reg[135]} {app_rd_data_reg[136]} {app_rd_data_reg[137]} {app_rd_data_reg[138]} {app_rd_data_reg[139]} {app_rd_data_reg[140]} {app_rd_data_reg[141]} {app_rd_data_reg[142]} {app_rd_data_reg[143]} {app_rd_data_reg[144]} {app_rd_data_reg[145]} {app_rd_data_reg[146]} {app_rd_data_reg[147]} {app_rd_data_reg[148]} {app_rd_data_reg[149]} {app_rd_data_reg[150]} {app_rd_data_reg[151]} {app_rd_data_reg[152]} {app_rd_data_reg[153]} {app_rd_data_reg[154]} {app_rd_data_reg[155]} {app_rd_data_reg[156]} {app_rd_data_reg[157]} {app_rd_data_reg[158]} {app_rd_data_reg[159]} {app_rd_data_reg[160]} {app_rd_data_reg[161]} {app_rd_data_reg[162]} {app_rd_data_reg[163]} {app_rd_data_reg[164]} {app_rd_data_reg[165]} {app_rd_data_reg[166]} {app_rd_data_reg[167]} {app_rd_data_reg[168]} {app_rd_data_reg[169]} {app_rd_data_reg[170]} {app_rd_data_reg[171]} {app_rd_data_reg[172]} {app_rd_data_reg[173]} {app_rd_data_reg[174]} {app_rd_data_reg[175]} {app_rd_data_reg[176]} {app_rd_data_reg[177]} {app_rd_data_reg[178]} {app_rd_data_reg[179]} {app_rd_data_reg[180]} {app_rd_data_reg[181]} {app_rd_data_reg[182]} {app_rd_data_reg[183]} {app_rd_data_reg[184]} {app_rd_data_reg[185]} {app_rd_data_reg[186]} {app_rd_data_reg[187]} {app_rd_data_reg[188]} {app_rd_data_reg[189]} {app_rd_data_reg[190]} {app_rd_data_reg[191]} {app_rd_data_reg[192]} {app_rd_data_reg[193]} {app_rd_data_reg[194]} {app_rd_data_reg[195]} {app_rd_data_reg[196]} {app_rd_data_reg[197]} {app_rd_data_reg[198]} {app_rd_data_reg[199]} {app_rd_data_reg[200]} {app_rd_data_reg[201]} {app_rd_data_reg[202]} {app_rd_data_reg[203]} {app_rd_data_reg[204]} {app_rd_data_reg[205]} {app_rd_data_reg[206]} {app_rd_data_reg[207]} {app_rd_data_reg[208]} {app_rd_data_reg[209]} {app_rd_data_reg[210]} {app_rd_data_reg[211]} {app_rd_data_reg[212]} {app_rd_data_reg[213]} {app_rd_data_reg[214]} {app_rd_data_reg[215]} {app_rd_data_reg[216]} {app_rd_data_reg[217]} {app_rd_data_reg[218]} {app_rd_data_reg[219]} {app_rd_data_reg[220]} {app_rd_data_reg[221]} {app_rd_data_reg[222]} {app_rd_data_reg[223]} {app_rd_data_reg[224]} {app_rd_data_reg[225]} {app_rd_data_reg[226]} {app_rd_data_reg[227]} {app_rd_data_reg[228]} {app_rd_data_reg[229]} {app_rd_data_reg[230]} {app_rd_data_reg[231]} {app_rd_data_reg[232]} {app_rd_data_reg[233]} {app_rd_data_reg[234]} {app_rd_data_reg[235]} {app_rd_data_reg[236]} {app_rd_data_reg[237]} {app_rd_data_reg[238]} {app_rd_data_reg[239]} {app_rd_data_reg[240]} {app_rd_data_reg[241]} {app_rd_data_reg[242]} {app_rd_data_reg[243]} {app_rd_data_reg[244]} {app_rd_data_reg[245]} {app_rd_data_reg[246]} {app_rd_data_reg[247]} {app_rd_data_reg[248]} {app_rd_data_reg[249]} {app_rd_data_reg[250]} {app_rd_data_reg[251]} {app_rd_data_reg[252]} {app_rd_data_reg[253]} {app_rd_data_reg[254]} {app_rd_data_reg[255]}]]
set_property src_info {type:XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:2 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:2 line:46 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {app_cmd[0]} {app_cmd[1]} {app_cmd[2]}]]
set_property src_info {type:XDC file:2 line:47 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 256 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:2 line:50 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {app_wdf_data[0]} {app_wdf_data[1]} {app_wdf_data[2]} {app_wdf_data[3]} {app_wdf_data[4]} {app_wdf_data[5]} {app_wdf_data[6]} {app_wdf_data[7]} {app_wdf_data[8]} {app_wdf_data[9]} {app_wdf_data[10]} {app_wdf_data[11]} {app_wdf_data[12]} {app_wdf_data[13]} {app_wdf_data[14]} {app_wdf_data[15]} {app_wdf_data[16]} {app_wdf_data[17]} {app_wdf_data[18]} {app_wdf_data[19]} {app_wdf_data[20]} {app_wdf_data[21]} {app_wdf_data[22]} {app_wdf_data[23]} {app_wdf_data[24]} {app_wdf_data[25]} {app_wdf_data[26]} {app_wdf_data[27]} {app_wdf_data[28]} {app_wdf_data[29]} {app_wdf_data[30]} {app_wdf_data[31]} {app_wdf_data[32]} {app_wdf_data[33]} {app_wdf_data[34]} {app_wdf_data[35]} {app_wdf_data[36]} {app_wdf_data[37]} {app_wdf_data[38]} {app_wdf_data[39]} {app_wdf_data[40]} {app_wdf_data[41]} {app_wdf_data[42]} {app_wdf_data[43]} {app_wdf_data[44]} {app_wdf_data[45]} {app_wdf_data[46]} {app_wdf_data[47]} {app_wdf_data[48]} {app_wdf_data[49]} {app_wdf_data[50]} {app_wdf_data[51]} {app_wdf_data[52]} {app_wdf_data[53]} {app_wdf_data[54]} {app_wdf_data[55]} {app_wdf_data[56]} {app_wdf_data[57]} {app_wdf_data[58]} {app_wdf_data[59]} {app_wdf_data[60]} {app_wdf_data[61]} {app_wdf_data[62]} {app_wdf_data[63]} {app_wdf_data[64]} {app_wdf_data[65]} {app_wdf_data[66]} {app_wdf_data[67]} {app_wdf_data[68]} {app_wdf_data[69]} {app_wdf_data[70]} {app_wdf_data[71]} {app_wdf_data[72]} {app_wdf_data[73]} {app_wdf_data[74]} {app_wdf_data[75]} {app_wdf_data[76]} {app_wdf_data[77]} {app_wdf_data[78]} {app_wdf_data[79]} {app_wdf_data[80]} {app_wdf_data[81]} {app_wdf_data[82]} {app_wdf_data[83]} {app_wdf_data[84]} {app_wdf_data[85]} {app_wdf_data[86]} {app_wdf_data[87]} {app_wdf_data[88]} {app_wdf_data[89]} {app_wdf_data[90]} {app_wdf_data[91]} {app_wdf_data[92]} {app_wdf_data[93]} {app_wdf_data[94]} {app_wdf_data[95]} {app_wdf_data[96]} {app_wdf_data[97]} {app_wdf_data[98]} {app_wdf_data[99]} {app_wdf_data[100]} {app_wdf_data[101]} {app_wdf_data[102]} {app_wdf_data[103]} {app_wdf_data[104]} {app_wdf_data[105]} {app_wdf_data[106]} {app_wdf_data[107]} {app_wdf_data[108]} {app_wdf_data[109]} {app_wdf_data[110]} {app_wdf_data[111]} {app_wdf_data[112]} {app_wdf_data[113]} {app_wdf_data[114]} {app_wdf_data[115]} {app_wdf_data[116]} {app_wdf_data[117]} {app_wdf_data[118]} {app_wdf_data[119]} {app_wdf_data[120]} {app_wdf_data[121]} {app_wdf_data[122]} {app_wdf_data[123]} {app_wdf_data[124]} {app_wdf_data[125]} {app_wdf_data[126]} {app_wdf_data[127]} {app_wdf_data[128]} {app_wdf_data[129]} {app_wdf_data[130]} {app_wdf_data[131]} {app_wdf_data[132]} {app_wdf_data[133]} {app_wdf_data[134]} {app_wdf_data[135]} {app_wdf_data[136]} {app_wdf_data[137]} {app_wdf_data[138]} {app_wdf_data[139]} {app_wdf_data[140]} {app_wdf_data[141]} {app_wdf_data[142]} {app_wdf_data[143]} {app_wdf_data[144]} {app_wdf_data[145]} {app_wdf_data[146]} {app_wdf_data[147]} {app_wdf_data[148]} {app_wdf_data[149]} {app_wdf_data[150]} {app_wdf_data[151]} {app_wdf_data[152]} {app_wdf_data[153]} {app_wdf_data[154]} {app_wdf_data[155]} {app_wdf_data[156]} {app_wdf_data[157]} {app_wdf_data[158]} {app_wdf_data[159]} {app_wdf_data[160]} {app_wdf_data[161]} {app_wdf_data[162]} {app_wdf_data[163]} {app_wdf_data[164]} {app_wdf_data[165]} {app_wdf_data[166]} {app_wdf_data[167]} {app_wdf_data[168]} {app_wdf_data[169]} {app_wdf_data[170]} {app_wdf_data[171]} {app_wdf_data[172]} {app_wdf_data[173]} {app_wdf_data[174]} {app_wdf_data[175]} {app_wdf_data[176]} {app_wdf_data[177]} {app_wdf_data[178]} {app_wdf_data[179]} {app_wdf_data[180]} {app_wdf_data[181]} {app_wdf_data[182]} {app_wdf_data[183]} {app_wdf_data[184]} {app_wdf_data[185]} {app_wdf_data[186]} {app_wdf_data[187]} {app_wdf_data[188]} {app_wdf_data[189]} {app_wdf_data[190]} {app_wdf_data[191]} {app_wdf_data[192]} {app_wdf_data[193]} {app_wdf_data[194]} {app_wdf_data[195]} {app_wdf_data[196]} {app_wdf_data[197]} {app_wdf_data[198]} {app_wdf_data[199]} {app_wdf_data[200]} {app_wdf_data[201]} {app_wdf_data[202]} {app_wdf_data[203]} {app_wdf_data[204]} {app_wdf_data[205]} {app_wdf_data[206]} {app_wdf_data[207]} {app_wdf_data[208]} {app_wdf_data[209]} {app_wdf_data[210]} {app_wdf_data[211]} {app_wdf_data[212]} {app_wdf_data[213]} {app_wdf_data[214]} {app_wdf_data[215]} {app_wdf_data[216]} {app_wdf_data[217]} {app_wdf_data[218]} {app_wdf_data[219]} {app_wdf_data[220]} {app_wdf_data[221]} {app_wdf_data[222]} {app_wdf_data[223]} {app_wdf_data[224]} {app_wdf_data[225]} {app_wdf_data[226]} {app_wdf_data[227]} {app_wdf_data[228]} {app_wdf_data[229]} {app_wdf_data[230]} {app_wdf_data[231]} {app_wdf_data[232]} {app_wdf_data[233]} {app_wdf_data[234]} {app_wdf_data[235]} {app_wdf_data[236]} {app_wdf_data[237]} {app_wdf_data[238]} {app_wdf_data[239]} {app_wdf_data[240]} {app_wdf_data[241]} {app_wdf_data[242]} {app_wdf_data[243]} {app_wdf_data[244]} {app_wdf_data[245]} {app_wdf_data[246]} {app_wdf_data[247]} {app_wdf_data[248]} {app_wdf_data[249]} {app_wdf_data[250]} {app_wdf_data[251]} {app_wdf_data[252]} {app_wdf_data[253]} {app_wdf_data[254]} {app_wdf_data[255]}]]
set_property src_info {type:XDC file:2 line:51 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:2 line:54 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list app_en]]
set_property src_info {type:XDC file:2 line:55 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:2 line:58 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list app_rd_data_end]]
set_property src_info {type:XDC file:2 line:59 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:2 line:62 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list app_rd_data_valid]]
set_property src_info {type:XDC file:2 line:63 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:2 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:2 line:66 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list app_rdy]]
set_property src_info {type:XDC file:2 line:67 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:2 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list app_wdf_end]]
set_property src_info {type:XDC file:2 line:71 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:2 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:2 line:74 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list app_wdf_rdy]]
set_property src_info {type:XDC file:2 line:75 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:2 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:2 line:78 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list app_wdf_wren]]
set_property src_info {type:XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:2 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:2 line:82 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list ui_clk]]
set_property src_info {type:XDC file:2 line:83 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:2 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:2 line:86 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list write_state_flag]]
set_property src_info {type:XDC file:2 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:90 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets ui_clk]
