# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/vedio_sobel.xdc

# IP: ip/fifo_generator_0/fifo_generator_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# IP: ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: ip/rgb2dvi_0/rgb2dvi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rgb2dvi_0 || ORIG_REF_NAME==rgb2dvi_0} -quiet] -quiet

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet
