set_property SRC_FILE_INFO {cfile:C:/Users/Administrator/Desktop/K7325/DEMO/k705_fifo_ila_debug/k705_fifo_ila_debug.srcs/constrs_1/new/fifo_ila_debug.xdc rfile:../../../k705_fifo_ila_debug.srcs/constrs_1/new/fifo_ila_debug.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G22 [get_ports clk]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D26 [get_ports rstn]
