# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Administrator/Desktop/K7325/R5/SFP/k727_sfp12_gtx_10g/gtwizard_0_ex.srcs/sources_1/ip/gtwizard_0/gtwizard_0.xci
# IP: The module: 'gtwizard_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Administrator/Desktop/K7325/R5/SFP/k727_sfp12_gtx_10g/gtwizard_0_ex.srcs/sources_1/ip/gtwizard_0/gtwizard_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtwizard_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Administrator/Desktop/K7325/R5/SFP/k727_sfp12_gtx_10g/gtwizard_0_ex.srcs/sources_1/ip/gtwizard_0/gtwizard_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtwizard_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/Administrator/Desktop/K7325/R5/SFP/k727_sfp12_gtx_10g/gtwizard_0_ex.srcs/sources_1/ip/gtwizard_0/gtwizard_0.xci
# IP: The module: 'gtwizard_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Administrator/Desktop/K7325/R5/SFP/k727_sfp12_gtx_10g/gtwizard_0_ex.srcs/sources_1/ip/gtwizard_0/gtwizard_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtwizard_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Administrator/Desktop/K7325/R5/SFP/k727_sfp12_gtx_10g/gtwizard_0_ex.srcs/sources_1/ip/gtwizard_0/gtwizard_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtwizard_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
