set_property PACKAGE_PIN A23 [get_ports {led[0]}]
set_property PACKAGE_PIN A24 [get_ports {led[1]}]
set_property PACKAGE_PIN D23 [get_ports {led[2]}]
set_property PACKAGE_PIN C24 [get_ports {led[3]}]
set_property PACKAGE_PIN C26 [get_ports {led[4]}]
set_property PACKAGE_PIN D24 [get_ports {led[5]}]
set_property PACKAGE_PIN D25 [get_ports {led[6]}]
set_property PACKAGE_PIN E25 [get_ports {led[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN H26 [get_ports rstn]
set_property IOSTANDARD LVCMOS33 [get_ports rstn]
set_property PACKAGE_PIN G22 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports rgmii_rxc1]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_rxctl1]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_txc1]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_txctl1]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rxd1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rxd1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rxd1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rxd1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_txd1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_txd1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_txd1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_txd1[0]}]
set_property PACKAGE_PIN AA23 [get_ports rgmii_rxc1]
set_property PACKAGE_PIN U26 [get_ports rgmii_rxctl1]
set_property PACKAGE_PIN AB24 [get_ports rgmii_txc1]
set_property PACKAGE_PIN W23 [get_ports rgmii_txctl1]
set_property PACKAGE_PIN V22 [get_ports {rgmii_txd1[0]}]
set_property PACKAGE_PIN W26 [get_ports {rgmii_txd1[1]}]
set_property PACKAGE_PIN W25 [get_ports {rgmii_txd1[2]}]
set_property PACKAGE_PIN W21 [get_ports {rgmii_txd1[3]}]
set_property PACKAGE_PIN V26 [get_ports {rgmii_rxd1[0]}]
set_property PACKAGE_PIN V21 [get_ports {rgmii_rxd1[1]}]
set_property PACKAGE_PIN U24 [get_ports {rgmii_rxd1[2]}]
set_property PACKAGE_PIN U25 [get_ports {rgmii_rxd1[3]}]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list u1/util_gmii_to_rgmii_m0/gmii_tx_clk]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {u1/gmii_rxd[0]} {u1/gmii_rxd[1]} {u1/gmii_rxd[2]} {u1/gmii_rxd[3]} {u1/gmii_rxd[4]} {u1/gmii_rxd[5]} {u1/gmii_rxd[6]} {u1/gmii_rxd[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {u1/gmii_txd[0]} {u1/gmii_txd[1]} {u1/gmii_txd[2]} {u1/gmii_txd[3]} {u1/gmii_txd[4]} {u1/gmii_txd[5]} {u1/gmii_txd[6]} {u1/gmii_txd[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {u1/pack_total_len[0]} {u1/pack_total_len[1]} {u1/pack_total_len[2]} {u1/pack_total_len[3]} {u1/pack_total_len[4]} {u1/pack_total_len[5]} {u1/pack_total_len[6]} {u1/pack_total_len[7]} {u1/pack_total_len[8]} {u1/pack_total_len[9]} {u1/pack_total_len[10]} {u1/pack_total_len[11]} {u1/pack_total_len[12]} {u1/pack_total_len[13]} {u1/pack_total_len[14]} {u1/pack_total_len[15]} {u1/pack_total_len[16]} {u1/pack_total_len[17]} {u1/pack_total_len[18]} {u1/pack_total_len[19]} {u1/pack_total_len[20]} {u1/pack_total_len[21]} {u1/pack_total_len[22]} {u1/pack_total_len[23]} {u1/pack_total_len[24]} {u1/pack_total_len[25]} {u1/pack_total_len[26]} {u1/pack_total_len[27]} {u1/pack_total_len[28]} {u1/pack_total_len[29]} {u1/pack_total_len[30]} {u1/pack_total_len[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 2 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {u1/speed[0]} {u1/speed[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list u1/gmii_rx_clk]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list u1/gmii_rx_dv]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list u1/gmii_rx_er]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list u1/gmii_tx_clk]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list u1/gmii_tx_en]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list u1/gmii_tx_er]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list u1/link]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_gmii_tx_clk]
